name: Next.js Docker Build and Push
on:
  push:
    branches: [ "main" ]  # 當推送到 main 分支時觸發
  pull_request:
    branches: [ "main" ]  # 當對 main 分支發起 PR 時觸發
  workflow_dispatch:  # 允許手動觸發

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 最新版本

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: yarn install
      # 移除 --frozen-lockfile 選項，允許更新 yarn.lock

    - name: Build Next.js application
      run: yarn build
      env:
        # 設置構建時需要的環境變數
        NODE_ENV: production
        API: ${{ secrets.API_URL }}
        RAG_API: ${{ secrets.RAG_API }}
        NEXT_PUBLIC_DOMAIN: ${{ secrets.DOMAIN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: s225002731650/ishafrontend:latest
        build-args: |
          NODE_ENV=production
          API_URL=${{ secrets.API_URL }}
          RAG_API=${{ secrets.RAG_API }}
          NEXT_PUBLIC_DOMAIN=${{ secrets.DOMAIN }}
        cache-from: type=registry,ref=s225002731650/ishafrontend:buildcache
        cache-to: type=registry,ref=s225002731650/ishafrontend:buildcache,mode=max
